# a_tensor_initialization.py

In [1]:
import torch

In [2]:
# torch.Tensor class
t1 = torch.Tensor([1, 2, 3], device='cpu')
print(t1.dtype)   # >>> torch.float32
print(t1.device)  # >>> cpu
print(t1.requires_grad)  # >>> False
print(t1.size())  # torch.Size([3])
print(t1.shape)   # torch.Size([3])

torch.float32
cpu
False
torch.Size([3])
torch.Size([3])


In [3]:
t1_cuda = t1.cuda()
print(t1_cuda.device)

cuda:0


In [4]:
# torch.tensor function
t2 = torch.tensor([1,2,3], device='cpu')
print(t2.dtype) # >>>torch.int64
print(t2.device) # >>> cpu
print(t2.requires_grad) # >>> False
print(t2.size())  # torch.Size([3])
print(t2.shape)  # torch.Size([3])

torch.int64
cpu
False
torch.Size([3])
torch.Size([3])


In [5]:
t2_cuda = t2.cuda()
print(t2_cuda.dtype) # >>>torch.int64
print(t2_cuda.device) # >>> cpu
print(t2_cuda.requires_grad) # >>> False
print(t2_cuda.size())  # torch.Size([3])
print(t2_cuda.shape)  # torch.Size([3])

torch.int64
cuda:0
False
torch.Size([3])
torch.Size([3])


In [6]:
a1 = torch.tensor(1)			     # shape: torch.Size([]), ndims(=rank): 0
print(a1.shape, a1.ndim)

torch.Size([]) 0


In [7]:
a2 = torch.tensor([1])		  	     # shape: torch.Size([1]), ndims(=rank): 1
print(a2.shape, a2.ndim)

torch.Size([1]) 1


In [8]:
a3 = torch.tensor([1, 2, 3, 4, 5])   # shape: torch.Size([5]), ndims(=rank): 1
print(a3.shape, a3.ndim)

torch.Size([5]) 1


In [9]:
a4 = torch.tensor([[1], [2], [3], [4], [5]])   # shape: torch.Size([5, 1]), ndims(=rank): 2
print(a4.shape, a4.ndim)

torch.Size([5, 1]) 2


In [10]:
a5 = torch.tensor([                 # shape: torch.Size([3, 2]), ndims(=rank): 2
    [1, 2],
    [3, 4],
    [5, 6]
])
print(a5.shape, a5.ndim)

torch.Size([3, 2]) 2


In [11]:
a6 = torch.tensor([                 # shape: torch.Size([3, 2, 1]), ndims(=rank): 3
    [[1], [2]],
    [[3], [4]],
    [[5], [6]]
])
print(a6.shape, a6.ndim)

torch.Size([3, 2, 1]) 3


In [13]:
a7 = torch.tensor([                 # shape: torch.Size([3, 1, 2, 1]), ndims(=rank): 4
    [[[1], [2]]],
    [[[3], [4]]],
    [[[5], [6]]]
])
print(a7.shape, a7.ndim)

torch.Size([3, 1, 2, 1]) 4


In [15]:
a8 = torch.tensor([                 # shape: torch.Size([3, 1, 2, 3]), ndims(=rank): 4
    [[[1, 2, 3], [2, 3, 4]]],
    [[[3, 1, 1], [4, 4, 5]]],
    [[[5, 6, 2], [6, 3, 1]]]
])
print(a8.shape, a8.ndim)

torch.Size([3, 1, 2, 3]) 4


In [16]:
a9 = torch.tensor([                 # shape: torch.Size([3, 1, 2, 3, 1]), ndims(=rank): 5
    [[[[1], [2], [3]], [[2], [3], [4]]]],
    [[[[3], [1], [1]], [[4], [4], [5]]]],
    [[[[5], [6], [2]], [[6], [3], [1]]]]
])
print(a9.shape, a9.ndim)

torch.Size([3, 1, 2, 3, 1]) 5


In [18]:
a10 = torch.tensor([                 # shape: torch.Size([4, 5]), ndims(=rank): 2
    [1, 2, 3, 4, 5],
    [1, 2, 3, 4, 5],
    [1, 2, 3, 4, 5],
    [1, 2, 3, 4, 5],
])
print(a10.shape, a10.ndim)

torch.Size([4, 5]) 2


In [20]:
a11 = torch.tensor([                 # ValueError: expected sequence of length 3 at dim 3 (got 2)
    [[[1, 2, 3], [4, 5]]],
    [[[1, 2, 3], [4, 5]]],
    [[[1, 2, 3], [4, 5]]],
    [[[1, 2, 3], [4, 5]]],
])

ValueError: expected sequence of length 3 at dim 3 (got 2)

# b_tensor_initialization_copy.py

In [23]:
import numpy as np

In [21]:
l1 = [1, 2, 3]
t1 = torch.Tensor(l1)

l2 = [1, 2, 3]
t2 = torch.tensor(l2)

l3 = [1, 2, 3]
t3 = torch.as_tensor(l3)

l1[0] = 100
l2[0] = 100
l3[0] = 100

print(t1)
print(t2)
print(t3)

tensor([1., 2., 3.])
tensor([1, 2, 3])
tensor([1, 2, 3])


In [24]:
l4 = np.array([1, 2, 3])
t4 = torch.Tensor(l4)

l5 = np.array([1, 2, 3])
t5 = torch.tensor(l5)

l6 = np.array([1, 2, 3])
t6 = torch.as_tensor(l6)

l4[0] = 100
l5[0] = 100
l6[0] = 100

print(t4)
print(t5)
print(t6)

tensor([1., 2., 3.])
tensor([1, 2, 3])
tensor([100,   2,   3])


# c_tensor_initialization_constant_values.py

In [25]:
t1 = torch.ones(size=(5,))  # or torch.ones(5)
t1_like = torch.ones_like(input=t1)
print(t1)  # >>> tensor([1., 1., 1., 1., 1.])
print(t1_like)  # >>> tensor([1., 1., 1., 1., 1.])

tensor([1., 1., 1., 1., 1.])
tensor([1., 1., 1., 1., 1.])


In [26]:
t2 = torch.zeros(size=(6,))  # or torch.zeros(6)
t2_like = torch.zeros_like(input=t2)
print(t2)  # >>> tensor([0., 0., 0., 0., 0., 0.])
print(t2_like)  # >>> tensor([0., 0., 0., 0., 0., 0.])

tensor([0., 0., 0., 0., 0., 0.])
tensor([0., 0., 0., 0., 0., 0.])


In [27]:
t3 = torch.empty(size=(4,))  # or torch.zeros(4)
t3_like = torch.empty_like(input=t3)
print(t3)  # >>> tensor([0., 0., 0., 0.])
print(t3_like)  # >>> tensor([0., 0., 0., 0.])

tensor([0.0000, 1.8750, 0.0000, 0.0000])
tensor([1.1376e-13, 8.8982e-43, 3.0000e+00, 0.0000e+00])


In [28]:
t4 = torch.eye(n=3)
print(t4)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])


# d_tensor_initialization_random_values.py

In [29]:
t1 = torch.randint(low=10, high=20, size=(1,2))
print(t1)

tensor([[16, 12]])


In [30]:
t2 = torch.rand(size=(1,3))
print(t2)

tensor([[0.4791, 0.4060, 0.6548]])


In [31]:
t3 = torch.randn(size=(1,3))
print(t3)

tensor([[ 0.0636, -1.0386, -0.4564]])


In [32]:
t4 = torch.normal(mean=10.0, std=1.0, size=(3,2))
print(t4)

tensor([[10.0401,  8.9724],
        [10.5785, 10.4772],
        [ 8.7702,  9.2034]])


In [33]:
t5 = torch.linspace(start=0.0, end=5.0, steps=3)
print(t5)

tensor([0.0000, 2.5000, 5.0000])


In [36]:
t6 = torch.arange(5)
print(t6)

tensor([0, 1, 2, 3, 4])


In [40]:
torch.manual_seed(1729) # 난수 발생 seed 고정
random1 = torch.rand(2,3)
print(random1)

tensor([[0.3126, 0.3791, 0.3087],
        [0.0736, 0.4216, 0.0691]])


In [38]:
random2 = torch.rand(2,3)
print(random2)

tensor([[0.2332, 0.4047, 0.2162],
        [0.9927, 0.4128, 0.5938]])


In [41]:
torch.manual_seed(1729)
random3 = torch.rand(2,3)
print(random3) # random1과 동일한 결과

tensor([[0.3126, 0.3791, 0.3087],
        [0.0736, 0.4216, 0.0691]])


In [42]:
random4 = torch.rand(2,3)
print(random4)

tensor([[0.2332, 0.4047, 0.2162],
        [0.9927, 0.4128, 0.5938]])


# e_tensor_type_conversion.py

In [43]:
a = torch.ones((2,3))
print(a.dtype)

torch.float32


In [44]:
b = torch.ones((2,3), dtype=torch.int16)
print(b)

tensor([[1, 1, 1],
        [1, 1, 1]], dtype=torch.int16)


In [45]:
c = torch.rand((2,3), dtype=torch.float64) * 20
print(c)

tensor([[18.0429,  7.2532, 19.6519],
        [10.8626,  2.1505, 19.6913]], dtype=torch.float64)


In [46]:
d = b.to(torch.int32)
print(d)

tensor([[1, 1, 1],
        [1, 1, 1]], dtype=torch.int32)


In [47]:
double_d = torch.ones(10, 2, dtype=torch.double)
short_e = torch.tensor([[1,2]], dtype=torch.short)
print(double_d.dtype)
print(short_e.dtype)

torch.float64
torch.int16


In [48]:
double_d = torch.zeros(10, 2).double()
short_e = torch.ones(10, 2).short()
print(double_d.dtype)
print(short_e.dtype)

torch.float64
torch.int16


In [49]:
double_d = torch.zeros(10, 2).to(torch.double)
short_e = torch.ones(10, 2).to(dtype=torch.short)
print(double_d.dtype)
print(short_e.dtype)

torch.float64
torch.int16


In [50]:
double_d = torch.zeros(10, 2).type(torch.double)
short_e = torch.ones(10, 2).type(dtype=torch.short)
print(double_d.dtype)
print(short_e.dtype)

torch.float64
torch.int16


In [51]:
double_f = torch.rand(5, dtype=torch.double)
short_g = double_f.to(torch.short)
print((double_f * short_g).dtype)

torch.float64


# f_tensor_operations.py

In [54]:
# 텐서 덧셈
t1 = torch.ones(size=(2,3))
t2 = torch.ones(size=(2,3))
t3 = torch.add(t1, t2)
t4 = t1 + t2
print(t3)
print(t4)

tensor([[2., 2., 2.],
        [2., 2., 2.]])
tensor([[2., 2., 2.],
        [2., 2., 2.]])


In [55]:
# 텐서 뺄셈
t5 = torch.sub(t1, t2)
t6 = t1 - t2
print(t5)
print(t6)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [56]:
# 텐서 곱셈
t7 = torch.mul(t1, t2)
t8 = t1 * t2
print(t7)
print(t8)

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [57]:
# 텐서 나눗셈
t9 = torch.div(t1, t2)
t10 = t1 / t2
print(t9)
print(t10)

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])


# g_tensor_operations_mm.py

In [59]:
# torch.dot
# 1D 벡터 내적 전용
# 결과는 스칼라 (0-D 텐서)

t1 = torch.dot(
    torch.tensor([2,3]), torch.tensor([2,1])
)
print(t1, t1.size())

tensor(7) torch.Size([])


In [60]:
# torch.mm
# 2D 행렬곱 전용
# 입력 둘 다 2차원이어야 함
# 브로드캐스팅 없음

t2 = torch.randn(2,3)
t3 = torch.randn(3,2)
print(t4, t4.shape)

tensor([[2., 2., 2.],
        [2., 2., 2.]]) torch.Size([2, 3])


In [62]:
# torch.bmm
# 3D (batch, n, m) × (batch, m, p) 전용
# 배치 크기 같아야 함
# 브로드캐스팅 없음 → 각 배치별로 독립적인 행렬곱

t5 = torch.randn(10, 3, 4)
t6 = torch. randn(10, 4, 5)
t7 = torch.bmm(t5, t6)
print(t7.shape)

torch.Size([10, 3, 5])


In [65]:
# torch.matmul / @ 연산자
# 범용 행렬곱 (1D, 2D, nD 다 가능)
# 규칙:
# 1D·1D → 내적
# 2D·2D → 행렬곱
# nD·mD → 마지막 2차원만 행렬곱, 앞 차원은 브로드캐스트 처리

# 1D
t8 = torch.matmul(torch.tensor([1,2,3]), torch.tensor([4,5,6]))
print(t8.shape)

torch.Size([])


In [66]:
# 2D
t9 = torch.matmul(t2, t3)
print(t9.shape)

torch.Size([2, 2])


In [67]:
# 3D 
t10 = torch.matmul(t5, t6)
t11 = torch.randn(1, 4, 5)
t12 = torch.randn(10, 5, 6)
t13 = torch.matmul(t11, t12)
print(t10.shape)
print(t13.shape)

torch.Size([10, 3, 5])
torch.Size([10, 4, 6])


In [69]:
# nD
t14 = torch.randn(5, 4, 3, 2)
t15 = torch.randn(5, 4, 2, 4)
t16 = torch.matmul(t14, t15)
t17 = torch.randn(2, 1, 4, 2, 3)
t18 = torch.randn(1, 3, 4, 3, 5)
t19 = torch.matmul(t17, t18)
print(t16.shape)
print(t19.shape)

torch.Size([5, 4, 3, 4])
torch.Size([2, 3, 4, 2, 5])


# h_tensor_operations_matmul.py

In [70]:
# vector x vector: dot product
t1 = torch.randn(3)
t2 = torch.randn(3)
print(torch.matmul(t1, t2).size())  # torch.Size([])

torch.Size([])


In [71]:
# matrix x vector: broadcasted dot
t3 = torch.randn(3, 4)
t4 = torch.randn(4)
print(torch.matmul(t3, t4).size())  # torch.Size([3])

torch.Size([3])


In [72]:
# batched matrix x vector: broadcasted dot
t5 = torch.randn(10, 3, 4)
t6 = torch.randn(4)
print(torch.matmul(t5, t6).size())  # torch.Size([10, 3])

torch.Size([10, 3])


In [73]:
# batched matrix x batched matrix: bmm
t7 = torch.randn(10, 3, 4)
t8 = torch.randn(10, 4, 5)
print(torch.matmul(t7, t8).size())  # torch.Size([10, 3, 5])

torch.Size([10, 3, 5])


In [74]:
# batched matrix x matrix: bmm
t9 = torch.randn(10, 3, 4)
t10 = torch.randn(4, 5)
print(torch.matmul(t9, t10).size())  # torch.Size([10, 3, 5])

torch.Size([10, 3, 5])


# i_tensor_broadcasting.py

In [75]:
t1 = torch.tensor([1.0, 2.0, 3.0])
t2 = 2.0
print(t1 * t2)
print((t1*t2).shape)

tensor([2., 4., 6.])
torch.Size([3])


In [77]:
t3 = torch.tensor([[0, 1], [2, 4], [10, 10]])
t4 = torch.tensor([4, 5])
print(t3 - t4)
print((t3 - t4).shape)

tensor([[-4, -4],
        [-2, -1],
        [ 6,  5]])
torch.Size([3, 2])


In [79]:
t5 = torch.tensor([[1., 2.], [3., 4.]])
print(t5 + 2.0)  # t5.add(2.0)
print(t5 - 2.0)  # t5.sub(2.0)
print(t5 * 2.0)  # t5.mul(2.0)
print(t5 / 2.0)  # t5.div(2.0)

tensor([[3., 4.],
        [5., 6.]])
tensor([[-1.,  0.],
        [ 1.,  2.]])
tensor([[2., 4.],
        [6., 8.]])
tensor([[0.5000, 1.0000],
        [1.5000, 2.0000]])


In [80]:
def normalize(x):
  return x / 255


t6 = torch.randn(3, 28, 28)
print(normalize(t6).size())

torch.Size([3, 28, 28])


In [81]:
t7 = torch.tensor([[1, 2], [0, 3]])  # torch.Size([2, 2])
t8 = torch.tensor([[3, 1]])  # torch.Size([1, 2])
t9 = torch.tensor([[5], [2]])  # torch.Size([2, 1])
t10 = torch.tensor([7])  # torch.Size([1])
print(t7 + t8)   # >>> tensor([[4, 3], [3, 4]])
print(t7 + t9)   # >>> tensor([[6, 7], [2, 5]])
print(t8 + t9)   # >>> tensor([[8, 6], [5, 3]])
print(t7 + t10)  # >>> tensor([[ 8, 9], [ 7, 10]])

tensor([[4, 3],
        [3, 4]])
tensor([[6, 7],
        [2, 5]])
tensor([[8, 6],
        [5, 3]])
tensor([[ 8,  9],
        [ 7, 10]])


In [82]:
t11 = torch.ones(4, 3, 2)
t12 = t11 * torch.rand(3, 2)  # 3rd & 2nd dims identical to t11, dim 0 absent
print(t12.shape)

torch.Size([4, 3, 2])


In [83]:
t13 = torch.ones(4, 3, 2)
t14 = t13 * torch.rand(3, 1)  # 3rd dim = 1, 2nd dim is identical to t13
print(t14.shape)

torch.Size([4, 3, 2])


In [84]:
t15 = torch.ones(4, 3, 2)
t16 = t15 * torch.rand(1, 2)  # 3rd dim is identical to t15, 2nd dim is 1
print(t16.shape)

torch.Size([4, 3, 2])


In [85]:
t17 = torch.ones(5, 3, 4, 1)
t18 = torch.rand(3, 1, 1)  # 2nd dim is identical to t17, 3rd and 4th dims are 1
print((t17 + t18).size())

torch.Size([5, 3, 4, 1])


In [86]:
t19 = torch.empty(5, 1, 4, 1)
t20 = torch.empty(3, 1, 1)
print((t19 + t20).size())  # torch.Size([5, 3, 4, 1])

torch.Size([5, 3, 4, 1])


In [87]:
t21 = torch.empty(1)
t22 = torch.empty(3, 1, 7)
print((t21 + t22).size())  # torch.Size([3, 1, 7])

torch.Size([3, 1, 7])


In [88]:
t23 = torch.ones(3, 3, 3)
t24 = torch.ones(3, 1, 3)
print((t23 + t24).size())  # torch.Size([3, 3, 3])

torch.Size([3, 3, 3])


In [89]:
t25 = torch.empty(5, 2, 4, 1)
t26 = torch.empty(3, 1, 1)
print((t25 + t26).size())
# RuntimeError: The size of tensor a (2) must match
# the size of tensor b (3) at non-singleton dimension 1

RuntimeError: The size of tensor a (2) must match the size of tensor b (3) at non-singleton dimension 1

In [90]:
t27 = torch.ones(4) * 5
print(t27)  # >>> tensor([ 5, 5, 5, 5])

tensor([5., 5., 5., 5.])


In [91]:
t28 = torch.pow(t27, 2)
print(t28)  # >>> tensor([ 25, 25, 25, 25])

tensor([25., 25., 25., 25.])


In [92]:
exp = torch.arange(1., 5.)  # tensor([ 1.,  2.,  3.,  4.])
a = torch.arange(1., 5.)  # tensor([ 1.,  2.,  3.,  4.])
t29 = torch.pow(a, exp)
print(t29)  # >>> tensor([   1.,    4.,   27.,  256.])

tensor([  1.,   4.,  27., 256.])


# j_tensor_indexing_slicing.py

In [94]:
x = torch.tensor(
  [[0, 1, 2, 3, 4],
   [5, 6, 7, 8, 9],
   [10, 11, 12, 13, 14]]
)

print(x[1])  # >>> tensor([5, 6, 7, 8, 9])
print(x[:, 1])  # >>> tensor([1, 6, 11])
print(x[1, 2])  # >>> tensor(7)
print(x[:, -1])  # >>> tensor([4, 9, 14)

tensor([5, 6, 7, 8, 9])
tensor([ 1,  6, 11])
tensor(7)
tensor([ 4,  9, 14])


In [95]:
print(x[1:])  # >>> tensor([[ 5,  6,  7,  8,  9], [10, 11, 12, 13, 14]])
print(x[1:, 3:])  # >>> tensor([[ 8,  9], [13, 14]])

tensor([[ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]])
tensor([[ 8,  9],
        [13, 14]])


In [96]:
y = torch.zeros((6,6))
y[1:4, 2] = 1
print(y)

print(y[1:4, 1:4])

tensor([[0., 0., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]])
tensor([[0., 1., 0.],
        [0., 1., 0.],
        [0., 1., 0.]])


In [97]:
z = torch.tensor(
  [[1, 2, 3, 4],
   [2, 3, 4, 5],
   [5, 6, 7, 8]]
)
print(z[:2])
print(z[1:, 1:3])
print(z[:, 1:])

z[1:, 1:3] = 0
print(z)

tensor([[1, 2, 3, 4],
        [2, 3, 4, 5]])
tensor([[3, 4],
        [6, 7]])
tensor([[2, 3, 4],
        [3, 4, 5],
        [6, 7, 8]])
tensor([[1, 2, 3, 4],
        [2, 0, 0, 5],
        [5, 0, 0, 8]])


# k_tensor_reshaping.py

In [101]:
t1 = torch.tensor([[1, 2, 3], [4, 5, 6]])
t2 = t1.view(3, 2)  # Shape becomes (3, 2)
t3 = t1.reshape(1, 6)  # Shape becomes (1, 6)
print(t2)
print(t3)

tensor([[1, 2],
        [3, 4],
        [5, 6]])
tensor([[1, 2, 3, 4, 5, 6]])


In [99]:
t4 = torch.arange(8).view(2, 4)  # Shape becomes (2, 4)
t5 = torch.arange(6).view(2, 3)  # Shape becomes (2, 3)
print(t4)
print(t5)

tensor([[0, 1, 2, 3],
        [4, 5, 6, 7]])
tensor([[0, 1, 2],
        [3, 4, 5]])


In [102]:
# Original tensor with shape (1, 3, 1)
t6 = torch.tensor([[[1], [2], [3]]])

# Remove all dimensions of size 1
t7 = t6.squeeze()  # Shape becomes (3,)

# Remove dimension at position 0
t8 = t6.squeeze(0)  # Shape becomes (3, 1)
print(t7)
print(t8)

tensor([1, 2, 3])
tensor([[1],
        [2],
        [3]])


In [103]:
# Original tensor with shape (3,)
t9 = torch.tensor([1, 2, 3])

# Add a new dimension at position 1
t10 = t9.unsqueeze(1)  # Shape becomes (3, 1)
print(t10)

tensor([[1],
        [2],
        [3]])


In [104]:
t11 = torch.tensor(
  [[1, 2, 3],
   [4, 5, 6]]
)
t12 = t11.unsqueeze(1)  # Shape becomes (2, 1, 3)
print(t12, t12.shape)

tensor([[[1, 2, 3]],

        [[4, 5, 6]]]) torch.Size([2, 1, 3])


In [105]:
# Original tensor with shape (2, 3)
t13 = torch.tensor([[1, 2, 3], [4, 5, 6]])

# Flatten the tensor
t14 = t13.flatten()  # Shape becomes (6,)

print(t14)

tensor([1, 2, 3, 4, 5, 6])


In [106]:
# Original tensor with shape (2, 2, 2)
t15 = torch.tensor([[[1, 2],
                     [3, 4]],
                    [[5, 6],
                     [7, 8]]])
t16 = torch.flatten(t15)

t17 = torch.flatten(t15, start_dim=1)

print(t16)
print(t17)

tensor([1, 2, 3, 4, 5, 6, 7, 8])
tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])


In [107]:
t17 = t15.flatten(end_dim=1)
print(t17)

tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])


In [108]:
t18 = torch.randn(2, 3, 5)
print(t18.shape)  # >>> torch.Size([2, 3, 5])
print(torch.permute(t18, (2, 0, 1)).size())  # >>> torch.Size([5, 2, 3])

torch.Size([2, 3, 5])
torch.Size([5, 2, 3])


In [109]:
# Original tensor with shape (2, 3)
t19 = torch.tensor([[1, 2, 3], [4, 5, 6]])

# Permute the dimensions
t20 = torch.permute(t19, dims=(0, 1))  # Shape becomes (2, 3) still
t21 = torch.permute(t19, dims=(1, 0))  # Shape becomes (3, 2)
print(t20)
print(t21)

tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([[1, 4],
        [2, 5],
        [3, 6]])


In [111]:
# Transpose the tensor
t22 = torch.transpose(t19, 0, 1)  # Shape becomes (3, 2)

print(t22)

t23 = torch.t(t19)  # Shape becomes (3, 2), for 2d

print(t23)

tensor([[1, 4],
        [2, 5],
        [3, 6]])
tensor([[1, 4],
        [2, 5],
        [3, 6]])


# l_tensor_concat.py

In [117]:
# cat은 지정 축 외 나머지 차원의 크기가 같아야함
t1 = torch.zeros([2, 1, 3])
t2 = torch.zeros([2, 3, 3])
t3 = torch.zeros([2, 2, 3])

t4 = torch.cat([t1, t2, t3], dim=1)
print(t4.shape)

torch.Size([2, 6, 3])


In [113]:
t5 = torch.arange(0, 3)  # tensor([0, 1, 2])
t6 = torch.arange(3, 8)  # tensor([3, 4, 5, 6, 7])

t7 = torch.cat((t5, t6), dim=0)
print(t7.shape)  # >>> torch.Size([8])
print(t7)  # >>> tensor([0, 1, 2, 3, 4, 5, 6, 7])

torch.Size([8])
tensor([0, 1, 2, 3, 4, 5, 6, 7])


In [114]:
t8 = torch.arange(0, 6).reshape(2, 3)  # torch.Size([2, 3])
t9 = torch.arange(6, 12).reshape(2, 3)  # torch.Size([2, 3])

# 2차원 텐서간 병합
t10 = torch.cat((t8, t9), dim=0)
print(t10.size())  # >>> torch.Size([4, 3])
print(t10)
# >>> tensor([[ 0,  1,  2],
#             [ 3,  4,  5],
#             [ 6,  7,  8],
#             [ 9, 10, 11]])

t11 = torch.cat((t8, t9), dim=1)
print(t11.size())  # >>>torch.Size([2, 6])
print(t11)
# >>> tensor([[ 0,  1,  2,  6,  7,  8],
#             [ 3,  4,  5,  9, 10, 11]])

torch.Size([4, 3])
tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]])
torch.Size([2, 6])
tensor([[ 0,  1,  2,  6,  7,  8],
        [ 3,  4,  5,  9, 10, 11]])


In [115]:
t12 = torch.arange(0, 6).reshape(2, 3)  # torch.Size([2, 3])
t13 = torch.arange(6, 12).reshape(2, 3)  # torch.Size([2, 3])
t14 = torch.arange(12, 18).reshape(2, 3)  # torch.Size([2, 3])

t15 = torch.cat((t12, t13, t14), dim=0)
print(t15.size())  # >>> torch.Size([6, 3])
print(t15)
# >>> tensor([[ 0,  1,  2],
#             [ 3,  4,  5],
#             [ 6,  7,  8],
#             [ 9, 10, 11],
#             [12, 13, 14],
#             [15, 16, 17]])

torch.Size([6, 3])
tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]])


In [116]:
t16 = torch.cat((t12, t13, t14), dim=1)
print(t16.size())  # >>> torch.Size([2, 9])
print(t16)
# >>> tensor([[ 0,  1,  2,  6,  7,  8, 12, 13, 14],
#             [ 3,  4,  5,  9, 10, 11, 15, 16, 17]])

torch.Size([2, 9])
tensor([[ 0,  1,  2,  6,  7,  8, 12, 13, 14],
        [ 3,  4,  5,  9, 10, 11, 15, 16, 17]])


In [118]:
t17 = torch.arange(0, 6).reshape(1, 2, 3)  # torch.Size([1, 2, 3])
t18 = torch.arange(6, 12).reshape(1, 2, 3)  # torch.Size([1, 2, 3])

t19 = torch.cat((t17, t18), dim=0)
print(t19.size())  # >>> torch.Size([2, 2, 3])
print(t19)
# >>> tensor([[[ 0,  1,  2],
#              [ 3,  4,  5]],
#             [[ 6,  7,  8],
#              [ 9, 10, 11]]])

torch.Size([2, 2, 3])
tensor([[[ 0,  1,  2],
         [ 3,  4,  5]],

        [[ 6,  7,  8],
         [ 9, 10, 11]]])


In [119]:
t20 = torch.cat((t17, t18), dim=1)
print(t20.size())  # >>> torch.Size([1, 4, 3])
print(t20)
# >>> tensor([[[ 0,  1,  2],
#              [ 3,  4,  5],
#              [ 6,  7,  8],
#              [ 9, 10, 11]]])

torch.Size([1, 4, 3])
tensor([[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8],
         [ 9, 10, 11]]])


In [120]:
t21 = torch.cat((t17, t18), dim=2)
print(t21.size())  # >>> torch.Size([1, 2, 6])
print(t21)
# >>> tensor([[[ 0,  1,  2,  6,  7,  8],
#              [ 3,  4,  5,  9, 10, 11]]])

torch.Size([1, 2, 6])
tensor([[[ 0,  1,  2,  6,  7,  8],
         [ 3,  4,  5,  9, 10, 11]]])


# m_tensor_stacking.py

In [121]:
t1 = torch.tensor([[1, 2, 3], [4, 5, 6]])
t2 = torch.tensor([[7, 8, 9], [10, 11, 12]])

t3 = torch.stack([t1, t2], dim=0)
t4 = torch.cat([t1.unsqueeze(dim=0), t2.unsqueeze(dim=0)], dim=0)
print(t3.shape, t3.equal(t4))

t5 = torch.stack([t1, t2], dim=1)
t6 = torch.cat([t1.unsqueeze(dim=1), t2.unsqueeze(dim=1)], dim=1)
print(t5.shape, t5.equal(t6))

t7 = torch.stack([t1, t2], dim=2)
t8 = torch.cat([t1.unsqueeze(dim=2), t2.unsqueeze(dim=2)], dim=2)
print(t7.shape, t7.equal(t8))

torch.Size([2, 2, 3]) True
torch.Size([2, 2, 3]) True
torch.Size([2, 3, 2]) True


In [122]:
t9 = torch.arange(0, 3)  # tensor([0, 1, 2])
t10 = torch.arange(3, 6)  # tensor([3, 4, 5])

print(t9.size(), t10.size())
# >>> torch.Size([3]) torch.Size([3])

torch.Size([3]) torch.Size([3])


In [123]:
t11 = torch.stack((t9, t10), dim=0)
print(t11.size())  # >>> torch.Size([2,3])
print(t11)
# >>> tensor([[0, 1, 2],
#             [3, 4, 5]])

torch.Size([2, 3])
tensor([[0, 1, 2],
        [3, 4, 5]])


In [126]:
t12 = torch.cat((t9.unsqueeze(0), t10.unsqueeze(0)), dim=0)
print(t11.equal(t12))

True


In [127]:
t13 = torch.stack((t9, t10), dim=1)
print(t13.size())
print(t13)

torch.Size([3, 2])
tensor([[0, 3],
        [1, 4],
        [2, 5]])


In [129]:
t14 = torch.cat((t9.unsqueeze(1), t10.unsqueeze(1)), dim=1)
print(t13.equal(t14))

True


# n_tensor_vstack_hstack.py

In [130]:
# vstack
# 세로로 쌓기
# 1D → 먼저 (n,) → (1,n) 으로 해석 후 dim=0 기준으로 이어붙임
# 2D 이상 → 무조건 dim=0

t1 = torch.tensor([1, 2, 3])
t2 = torch.tensor([4, 5, 6])
t3 = torch.vstack((t1, t2))
print(t3)
# >>> tensor([[1, 2, 3],
#             [4, 5, 6]])

tensor([[1, 2, 3],
        [4, 5, 6]])


In [132]:
# hstack
# 가로로 쌓기
# 1D → 그냥 1D로 이어붙임 (dim=0)
# 2D 이상 → dim=1 기준으로 이어붙임

t4 = torch.tensor([[1], [2], [3]])
t5 = torch.tensor([[4], [5], [6]])
t6 = torch.vstack((t4, t5))
print(t6)
# >>> tensor([[1],
#             [2],
#             [3],
#             [4],
#             [5],
#             [6]])

tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6]])


In [136]:
t7 = torch.tensor([
    [[1, 2, 3], [4, 5, 6]],
    [[7, 8, 9], [10, 11, 12]]
])
print(t7.shape)

torch.Size([2, 2, 3])


In [137]:
t8 = torch.tensor([
  [[13, 14, 15], [16, 17, 18]],
  [[19, 20, 21], [22, 23, 24]]
])
print(t8.shape)
# >>> (2, 2, 3)

torch.Size([2, 2, 3])


In [139]:
t9 = torch.vstack((t7, t8))
print(t9.shape)
print(t9)

torch.Size([4, 2, 3])
tensor([[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]],

        [[13, 14, 15],
         [16, 17, 18]],

        [[19, 20, 21],
         [22, 23, 24]]])


In [140]:
t10 = torch.tensor([1, 2, 3])
t11 = torch.tensor([4, 5, 6])
t12 = torch.hstack((t10, t11))
print(t12)
# >>> tensor([1, 2, 3, 4, 5, 6])

tensor([1, 2, 3, 4, 5, 6])


In [141]:
t13 = torch.tensor([[1], [2], [3]])
t14 = torch.tensor([[4], [5], [6]])
t15 = torch.hstack((t13, t14))
print(t15)
# >>> tensor([[1, 4],
#             [2, 5],
#             [3, 6]])

tensor([[1, 4],
        [2, 5],
        [3, 6]])


In [142]:
t16 = torch.tensor([
  [[1, 2, 3], [4, 5, 6]],
  [[7, 8, 9], [10, 11, 12]]
])
print(t16.shape)
# >>> (2, 2, 3)

torch.Size([2, 2, 3])


In [143]:
t17 = torch.tensor([
  [[13, 14, 15], [16, 17, 18]],
  [[19, 20, 21], [22, 23, 24]]
])
print(t17.shape)
# >>> (2, 2, 3)

torch.Size([2, 2, 3])


In [144]:
t18 = torch.hstack([t16, t17])
print(t18.shape)
# >>> (2, 4, 3)

print(t18)
# >>> tensor([[[ 1,  2,  3],
#              [ 4,  5,  6],
#              [13, 14, 15],
#              [16, 17, 18]],
#             [[ 7,  8,  9],
#              [10, 11, 12],
#              [19, 20, 21],
#              [22, 23, 24]]])


torch.Size([2, 4, 3])
tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [13, 14, 15],
         [16, 17, 18]],

        [[ 7,  8,  9],
         [10, 11, 12],
         [19, 20, 21],
         [22, 23, 24]]])


# 과제 후기
이번 과제에서는 PyTorch 텐서를 다루는 전반적인 방법을 실습했다. 먼저 torch.tensor, torch.empty, torch.ones, torch.arange, torch.rand, torch.randn 등을 사용하여 여러 방식으로 텐서를 초기화하였다. 이 과정에서 torch.tensor와 torch.as_tensor의 차이가 단순히 함수 이름의 차이가 아니라, 넘파이 배열을 그대로 메모리 공유하느냐, 아니면 새로 복사하느냐의 차이라는 점을 알게 되었다.  
그 다음으로는 타입 변환을 통해 정수, 실수, 불리언 등 다양한 자료형으로 텐서를 바꾸는 방법을 실습했다. 이어서 기본적인 산술 연산과 행렬 곱 연산을 다루었는데 이때 torch.dot, torch.mm, torch.matmul, torch.bmm 함수들이 모두 곱셈을 수행하지만, 각각 1차원 벡터, 2차원 행렬, 브로드캐스팅을 포함한 일반 연산, 3차원 배치 행렬에 따라 다르게 동작한다는 점을 확인하였다. 이를 통해 텐서의 차원과 연산 방식이 직접적으로 연결되어 있다는 사실을 명확히 이해할 수 있었다.  
브로드캐스팅 규칙도 실습하여 크기가 다른 텐서가 연산될 때 어느 축이 확장되는지 확인했고, 인덱싱과 슬라이싱을 통해 원하는 부분만 선택하는 방법을 익혔다. 이후 view, reshape, unsqueeze, squeeze 등을 사용하여 텐서의 모양을 자유롭게 변형하는 과정을 실습하였다.  
마지막으로 텐서를 합치거나 쌓는 방법을 다루었다. torch.cat은 단순히 주어진 축을 따라 텐서를 이어붙이는 방식이고, torch.stack은 새로운 차원을 추가하여 쌓는 방식이라는 차이를 알 수 있었다. 또한 vstack과 hstack을 통해 세로 방향과 가로 방향으로 텐서를 결합하는 방법을 비교하며, 차원 선택이 잘못되면 에러가 발생한다는 점도 확인할 수 있었다.  
이번 과제를 통해 단순히 텐서를 생성하고 조작하는 것에 그치지 않고, 실습 중 생긴 의문점을 질문하고 답을 확인하면서 함수별 차이와 동작 원리까지 정리할 수 있었다. 그 결과 텐서 초기화, 타입 변환, 연산, 브로드캐스팅, 인덱싱·슬라이싱, 차원 변형, 결합까지 다양한 PyTorch텐서 조작법을 이해할 수 있었다.  